### ISSUE TITLE
update the website URL

### ISSUE THREAD

**Issue by atefBB** [adaroobi/php-the-right-way#4]
The current URL of the website is http://www.phptherightway.com not http://www.php-the-right-way.com (in the description of the project).

**Comment by adaroobi** [comment]
Done, thank you.

**Comment by atefBB** [comment]
^__^ Happy to be in service!

**Comment by atefBB** [comment]
لماذا لا يكون رابط النسخة العربية مباشرة https://adaroobi.github.io/php-the-right-way/ ؟

**Comment by adaroobi** [comment]
هل تقصد
https://adaroobi.github.io/phptherightway/
?

**Comment by atefBB** [comment]
نعم.

**Comment by adaroobi** [comment]
لكي يكون متوافقاً مع مصدر المحتوى الأصلي:
https://github.com/codeguy/php-the-right-way
